version: '3'

services:
  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80

  server:
    image: node:18-alpine
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - sh
      - -c
      - |
        node server_pool.js
    